### ISSUE TITLE
Cannot add more than 2 custom commands

### ISSUE THREAD

**Issue by arabezar** [stefankueng/tools#10]
Unfortunately, when adding any 3rd user custom command (in addition to the standard ones) in Options, only 2 user custom commands remain after saving (the newest one and one of two existing).

**Comment by stefankueng** [comment]
I have 5 custom commands in my setup, so it works for me. Is there anything special about your setup?

**Comment by arabezar** [comment]
I'm so sorry for no reply for so long
I've moved to the newest version and the problem is gone.
Thanks a lot for the tool!!! Really great job!

BTW, I couldn't move my 1st custom command position in the list to any other position than 1st. Others (custom commands) can be moved.
Anyway I can live with this. So my all custom commands always go 1st in the whole list.
