### ISSUE TITLE
"Start in" "%curdir" for custom command causes the program not to launch

### ISSUE THREAD

**Issue by MarkCanada** [stefankueng/tools#12]
Love the program and just started to add custom commands.
When I leave "Start in" empty the program launches, but if I set it to "%curdir" with or without the apostrophes the program/command doesn't start for me.

**Comment by stefankueng** [comment]
%curdir is not a program. If you want to start another explorer instance at that path, use "explorer /f %curdir" instead.

**Comment by MarkCanada** [comment]
It's not about explorer. Please see screenshot below.
When "Start In: %curdir" is filled in the program doesn't start any more:

![screenshot](https://user-images.githubusercontent.com/5258515/56756372-7f24ca80-6746-11e9-94ba-2f4262745c60.png)

**Comment by stefankueng** [comment]
Leave "Start In:" empty: the default when left empty is the current directory.
And FYI: there's no variable replacement done for the "Start In:" field - it's used as is.
