### ISSUE TITLE
black background in Windows 10 1903

### ISSUE THREAD

**Issue by KHeresy** [stefankueng/tools#14]
After update to Windows 10 1903, the background of StExBar in Explorer become black.

**Comment by stefankueng** [comment]
that should only happen if you have enabled dark mode in the system settings. But then the explorer also shows up black.

**Comment by KHeresy** [comment]
It looks the same under dark mdoe and light mode.
The background of text "StEx" is light color, others are black


![stexbar-wrong-bgcolor](https://user-images.githubusercontent.com/1277610/56543900-75179600-65a5-11e9-8508-2972e46a194f.jpg)

**Comment by stefankueng** [comment]
Don't have version 1903 yet, so I guess that's why it still works properly for me.
![lightmode](https://user-images.githubusercontent.com/665591/56635229-33e6bb00-6665-11e9-83d0-78900acfbf58.png)
I'll have a look as soon as 1903 gets released.

**Comment by KHeresy** [comment]
Thanks for your reply.

**Comment by stefankueng** [comment]
please try this test version.

[bin.zip](https://github.com/stefankueng/tools/files/3115631/bin.zip)

**Comment by KHeresy** [comment]
Thanks for your test version.
StExBar upgrade to 1.10.0.1374, but nothing changed.
The background color sill wrong.

**Comment by KHeresy** [comment]
1.10.1.1378 still have problem on my computer.

There are two color modes in Windows 10 1903: default Windows Mode and default app mode.

The display result of 4 combination:

- Light Windows Mode and Dark App mode
![stexbar-l-d](https://user-images.githubusercontent.com/1277610/58144327-980a9800-7c80-11e9-8df5-f2fc7969ab7c.png)

- Light Windows Mode and Light App mode
![stexbar-l-l](https://user-images.githubusercontent.com/1277610/58144328-98a32e80-7c80-11e9-871d-c71ee1addfbf.png)

- Dark Windows Mode and Dark App mode
![stexbar-d-d](https://user-images.githubusercontent.com/1277610/58144329-98a32e80-7c80-11e9-9bbe-933018081d1f.png)

- Dark Windows Mode and Light App mode
![stexbar-d-l](https://user-images.githubusercontent.com/1277610/58144330-98a32e80-7c80-11e9-8955-93da32c743ee.png)

**Comment by stefankueng** [comment]
Seems the undocumented ShouldAppsUseDarkMode() API does not return a proper bool. Only the first bit of the returned value indicates true/false.

**Comment by KHeresy** [comment]
Thank you very much.
It works fine now
