### ISSUE TITLE
[StExBar 1.10.2] Adjust Bar Color & Seperator Style broken in Dark Mode Windows 10 Version 1809 (Build 17763.503)

### ISSUE THREAD

**Issue by fuba82** [stefankueng/tools#17]
Hi there,  
i found your StExBar and it seems *__very__* usefull! :)  

But it would be nice to change the Colors to properly integrate in the Windows 10 Dark Mode.  
  
Because of now the "Black" Background looks a little ugly with a greyish Explorer ^^  
It also seems the "Seperators" are Broken in Windows 10 Dark Mode and the Bar Name "StEx" Background is still **white** in Dark Mode.  
  
Tested in Windows 10 Version 1809 (Build 17763.503)
 
Screenshot of the Bar in Dark Mode:
![image](https://user-images.githubusercontent.com/11580974/58750431-b0ee2700-8492-11e9-9fcc-0e5cd6a335c6.png)
 
Possibly you can add a **Custom Color** feature for the whole Bar and Font?

Maybe you also can add the Option to **individually** Show/Hide the Button Text for each Button (especially Options Button) and also Move/Show/Hide the **StEx** Text?  
  
I know all this is just Style and not priority but if no one ask it maybe never will be added ;)  

--

Anyway...
Great Project and please keep go on with it! :)

**Comment by stefankueng** [comment]
Hiding or styling the "StEx" text is not possible since that's a part of explorer itself, not the StExBar. So we can't do anything there.
As for the colors: this would require complete custom drawing all the controls. I most likely won't go there...

**Comment by fuba82** [comment]
Very sad to hear that!
But in the case you will fix the bug(s) its kinda useless for me to use the bar again.
I dont really like unfinished stuff.

Anyway thanks for the try!
bye
