### ISSUE TITLE
StExBar: Help Window metrics on 4K display

### ISSUE THREAD

**Issue by mjdl** [stefankueng/tools#18]
Using StExBar x64 1.10.2.1381, Windows 10 (1903) on notebook 4K display (3840x2160) set at 200% scaling in Windows settings.
Problem: the Options dialog's help window text metrics are not coordinated with the Windows scaling used on a high DPI display, the text is displayed at 100% but should be displayed at 200%, in other words double the size visible in the attached screen shot.

If the help window was displayed by a separate exe program, then the user could use the High DPI compatibility settings in the compatibility options sheet of Windows Explorer for that exe file, but of course that's not possible here.

The main options window pane text metric seems to be displayed correctly:

![StExBar-HelpWindow-HighDPI-Screen](https://user-images.githubusercontent.com/2262328/59287471-b8a28e00-8c3f-11e9-9801-f69614da4d74.png)

**Comment by stefankueng** [comment]
not sure I can fix this soon: seems explorer sets the dpi-awareness of extensions to 'not aware', and then the browser window doesn't scale because it's started from a non-dpi-aware context.

**Comment by mjdl** [comment]
Thank you for looking at the bug. I have no idea if there is some kind of API call that can set the DPI-awareness within the extension when it's activated (or whatever the appropriate terminology is...). High-DPI in MS Windows seems to be a bit of a mess!
