### ISSUE TITLE
Duplicate entries in context menu

### ISSUE THREAD

**Issue by gautxori-yuyu** [stefankueng/tools#23]
i get duplicate menu entries when right clicking on folders in the Windows 7 explorer left pane. This does not happen on right pane (the one showing both files and folders). Stex is the only duplicate entry.

I tried to use Nirsoft's ShellExView to find a solution, but the program shows only two entries: "Ie Toolbar" and "Context menu" (this one linked to the following extensions: Directory\Background, LibraryFolder\background, *, Directory, Drive, Folder, LibraryLocation, opensearchfilefolderresult)

Please provide a fix, and an explanation. Thanks.

**Comment by stefankueng** [comment]
That's a "feature" of explorer: one menu is shown for the selected item, one for it's parent folder.
But only if you either click in the right-pane on the background (not on a specific file/folder), or if as you have noticed click on a folder on the left pane.
Not really something we can do anything about.

**Comment by gautxori-yuyu** [comment]
Stefan, you can't be right: I've got a bunch of applications that set context menus in explorer, and none but yours creates double entries for their menus: say, 7zip, Winrar, Beyond Compare, TreSize Free, Everything, XnView, ...
There MUST be some way to fix that. It's up to you

**Comment by stefankueng** [comment]
That's because those register not for 'background'

**Comment by gautxori-yuyu** [comment]
I have at least one extension that registers for background, and works fine either in the left pane items, the right pane items or the background window: "Path Copy" (https://pathcopycopy.github.io/). Its source code is well commented. I would include links to screen captures but i think it's faster to install that extension and see.
