### ISSUE TITLE
Could you return the command to create the folder?

### ISSUE THREAD

**Issue by SunBoy2Heaven** [stefankueng/tools#25]
Could you return the command to create the folder?

**Comment by IanWorthington** [comment]
May I second this request?  (Or at least the return of the /icon/ to create a new folder, which is what I suspect the OP means?)

I know there's an official Windows icon to do that now, and I know it's been gone a long time, but I still miss having all the things I use regularly in the stexbar.

**Comment by stefankueng** [comment]
ok, I'll re-add the command, but make it hidden by default.
