### ISSUE TITLE
Rename on search results misses files

### ISSUE THREAD

**Issue by coezbek** [stefankueng/tools#28]
When using the regex rename function on a list of search results in the Windows Explorer the search replace is only applied to part of the entries if the replacement causes the search result to be removed due to the rename from the list of search results.

How to reproduce:
  - Create 10 Test files in a directory called "(1-10) Test.txt" (see attached [Test.zip](https://github.com/stefankueng/tools/files/3726066/Test.zip))
  - Search for these in the explorer by CTRL+F "Test"
  - Mark all and use Rename function to rename Test to e.g. Best
  - Observe that (depending on the speed of the PC) only part of the results get renamed and some entries rename as "*Test"

When looking at the code in [Rename.cpp,](https://github.com/stefankueng/tools/blob/master/StExBar/src/Rename.cpp) it seems that the code does not take into account that executing the rename could cause the number of entries to change:

```
if (SUCCEEDED(pFolderView->ItemCount(SVGIO_ALLVIEW, &nCount)))
{
    for (int i=0; i<nCount; ++i)
    {
        LPITEMIDLIST pidl;
        if (SUCCEEDED(pFolderView->Item(i, &pidl)))
        {
            // ... Rename 
```

Possible solutions:

- Iterate from nCount-1 to 0
- Check after each rename if ItemCount has become less than nCount.
- Don't perform the rename using pFolderView at all, but pass the path names of all selected items into the Rename Dialog and operate on the paths directly.

And of course: Thank you for the excellent StExBar!

**Comment by sklausing** [comment]
Run into the same issue often as well!
