### ISSUE TITLE
Windows Terminal Support

### ISSUE THREAD

**Issue by SadE54** [stefankueng/tools#29]
Hi , 

Could it be possible to support the news Windows Terminal ? (https://www.microsoft.com/fr-fr/p/windows-terminal-preview/9n0dx20hk701?activetab=pivot:overviewtab )
You can launch it using wt.exe in the Windows CLI or from  cmd
But when you're a trying add a custom command and select that executable from Stex, you're getting an error.
I think the problem is that the wt.exe is only a symbolic link (file size is zero) and i guess it should be manageg in a specific way by StEx

**Comment by dkalbertson** [comment]
@SadE54, I'm not sure if it helps, but I've had no problems adding Windows Terminal to my StexBar with Command line: `wt.exe -p %curdir`

**Comment by lbegue** [comment]
@SadE54 you may have a look at https://cmder.net/ 
(I use this tool since years and it belongs to my standard toolset)

suggestion: issue should be closed

**Comment by stefankueng** [comment]
`wt.exe -d %curdir`
works fine for me too.
