### ISSUE TITLE
StExBar installation failed on Windows 10 ver. 1909 (18363.476)

### ISSUE THREAD

**Issue by edvjacek** [stefankueng/tools#30]
Hi,

I've tried today to install StExBar64-1.10.2.msi on Windows 10 Pro ver. 1909 (18363.476). After the screen with the button "Install" (with the admin icon) I get a screen with the following message:

"StExBar Setup Wizard ended prematurely because of an error. Your system has been not modified. To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard."

The same problem if I try start the installer as administrator.

Any help? Where can I find logs of the installer?

Regards,
Jacek

**Comment by stefankueng** [comment]
you can run the msi installer manually: either open a console window or hit Windows+R and then enter
`msiexec /i "StExBar64-1.10.2.msi" /l*v "log.log"`
that will create a file containing log entries.

**Comment by edvjacek** [comment]
Hi Stefan,

thank you for the hint. I used it today and last night my computer was updated (now I have 18363.535) and, of course, the installation was without any problems...

Regards,
Jacek
