### ISSUE TITLE
quick search file in the current folder

### ISSUE THREAD

**Issue by parsibox** [stefankueng/tools#34]
hi
please add quick search or filter for search file name in current folder
just fast search

**Comment by stefankueng** [comment]
that's already implemented: at the very right of the toolbar there's an edit box. Depending on the settings (settings dialog) that box can do filtering.
Default settings are so that filtering works if you first type 'f', space then your filter string.

**Comment by parsibox** [comment]
![image](https://user-images.githubusercontent.com/12513476/75474969-26007580-59ad-11ea-9bc0-11739f8b7fab.png)
i test it but not work

**Comment by stefankueng** [comment]
As I said: it depends on your settings.
If you have the settings set to something other than "Filter" or "Auto" then of course the filter feature is disabled.
![image](https://user-images.githubusercontent.com/665591/75475097-791bfd80-5998-11ea-9118-1e83e09f4785.png)

**Comment by parsibox** [comment]
than you so much
