### ISSUE TITLE
Question about registration

### ISSUE THREAD

**Issue by amtopel** [stefankueng/tools#36]
I have a general question about Explorer tool band registration.  I was wondering why the registration that Stexbar uses does not result in Stexbar being loaded by Internet Explorer.  Based on Microsoft's tool band documentation, It seems like the tool band registration process is the same for Internet Explorer and File Explorer.  So I'm curious what might be different.  Thanks for any info.

**Comment by stefankueng** [comment]
An explorer toolbar has to implement the IDeskBand interface (CATID_DeskBand).
Internet Explorer toolbars either implement CATID_InfoBand or CATID_CommBand or both.

**Comment by amtopel** [comment]
Well according to the docs<https://docs.microsoft.com/en-us/previous-versions/bb776819(v=vs.85)?redirectedfrom=MSDN#band-object-basics>, “Tool bands use a different registration procedure and do not have a category identifier (CATID).”  So I don’t get it.  Can you provide any more info?
