### ISSUE TITLE
could you put up the new version of SKTimeStamp at sourceforge?

### ISSUE THREAD

**Issue by shirishag75** [stefankueng/tools#46]
Hi, 

I did see you did some changes to the utility about a year ago [1.] but somehow those changes were not replicated to the sourceforge site [2.], can you update it there, maybe with version 2020 or whatever you think is appropriate.  Thank you for the utility you provided.  - 

1. https://github.com/stefankueng/tools/tree/main/SKTimeStamp
2. https://sourceforge.net/projects/stefanstools/files/SKTimeStamp/

**Comment by stefankueng** [comment]
the new releases can be found here:
https://github.com/stefankueng/tools/releases
(scroll down until you find SKTimeStamp)
