### ISSUE TITLE
Detection of grepWin broken

### ISSUE THREAD

**Issue by FelixJirka** [stefankueng/tools#5]
Hello,

it looks like this commit [31eced54f8c793de4fc817d58efeddf34826573b](https://github.com/stefankueng/grepWin/commit/31eced54f8c793de4fc817d58efeddf34826573b) in the grepWin repo breaks the detection of grepWin at https://github.com/stefankueng/tools/blob/d4d96df28bf149290d5783eaa3974873ebaa3a8d/StExBar/src/OptionsDlg.cpp#L70

Would you consider an small update to the detection code?

**Comment by stefankueng** [comment]
fixed with rev 987836f21e318c8ca466905898d116ba74a37028
