### ISSUE TITLE
Feature request: Open Windows Terminal like Console/PS in StEx

### ISSUE THREAD

**Issue by lautjy** [stefankueng/tools#53]
Hi!

Support for Windows Terminal in StEx would be really great.
It's the console replacement from Microsoft: https://github.com/microsoft/terminal
It can open console / PS session inside it.

I can add it an element that opens Windows Terminal to the StEx menu, but cannot figure out how to "start in current folder".
This is the link I'm using to start it:

* `C:\Users\<USERNAME>\AppData\Local\Microsoft\WindowsApps\wt.exe -p "Command Prompt"`
* `C:\Users\<USERNAME>\AppData\Local\Microsoft\WindowsApps\wt.exe -p "PowerShell"`

**Comment by stefankueng** [comment]
don't specify a full path, just this:
`wt.exe -d %curdir`

and you're done.

**Comment by yp124202453** [comment]
thank you very much.

**Comment by yp124202453** [comment]
thank you very much.  @stefankueng
