### ISSUE TITLE
Question about the effect of Windows 11's Explorer tabs on shell events

### ISSUE THREAD

**Issue by amtopel** [stefankueng/tools#69]
Stefan,

This isn't really an issue about Stexbar.  I just had a question and thought you might know the answer.  Do you know how Windows 11's new Explorer tabs affect the shell object model and shell events?  For example, when the user selects a new tab, is there an event raised that you can capture via event sink?  Thanks for any info you might have.

**Comment by stefankueng** [comment]
there's no event raised. A new tab is like a new explorer instance, so an extension usually doesn't have to deal with it.
