### ISSUE TITLE
How to open CMD as administrator?

### ISSUE THREAD

**Issue by 4evermaat** [stefankueng/tools#8]
I tried to hold shift or ctrl before I click on the console toolbar button.  But the console is just a regular user.  I want to be able to open as administrator with one click.

![stefan explorer bar open console as administrator](https://user-images.githubusercontent.com/830306/49193708-aef7be00-f3b2-11e8-95f7-70900a36b1ed.png)

How do I do this  (open CMD as administrator)?

**Comment by stefankueng** [comment]
Hold down the Windows key, not the Shift or Ctrl key.
